name: cash_memo_creator
description: "Create a cash memo with few clicks"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.11.1
  shared_preferences: ^2.3.2
  printing: ^5.13.3
  path_provider: ^2.0.11
  flutter_localizations:  # Required for localization
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  toggle_switch: ^2.3.0
  image_picker: ^1.1.2
  permission_handler: ^10.2.0
  flutter_pdfview: ^1.3.3  # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true  # Enable code generation for localization
  assets:
    - assets/fonts/NotoSansBengali.ttf

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali.ttf

flutter_gen:
  l10n:
    arb-dir: lib/l10n  # Directory containing your .arb files for translations
    template-arb-file: app_en.arb  # Your template for the English language
    output-localization-file: l10n.dart  # Name of the generated file
    output-class: AppLocalizations  # Name of the localization class
    output-dir: lib/generated  # Directory for the generated localization file
