// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLSevZcpfGMFNEIn-FDfGpONa8FZL0Ac',
    appId: '1:1080350293673:web:d9ead443adccb9e6ed33b8',
    messagingSenderId: '1080350293673',
    projectId: 'admob-app-id-7000610218',
    authDomain: 'admob-app-id-7000610218.firebaseapp.com',
    databaseURL: 'https://admob-app-id-7000610218.firebaseio.com',
    storageBucket: 'admob-app-id-7000610218.appspot.com',
    measurementId: 'G-97PM85EM22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Vc-mwnH3ZsSB4zHfVh5bsINjyTR4YFE',
    appId: '1:1080350293673:android:09b5d5bb94af12d4ed33b8',
    messagingSenderId: '1080350293673',
    projectId: 'admob-app-id-7000610218',
    databaseURL: 'https://admob-app-id-7000610218.firebaseio.com',
    storageBucket: 'admob-app-id-7000610218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRWuPPpIK_NgQXKSKG8GsLaw9E_OF-bE',
    appId: '1:1080350293673:ios:adb33e8bd5a294c0ed33b8',
    messagingSenderId: '1080350293673',
    projectId: 'admob-app-id-7000610218',
    databaseURL: 'https://admob-app-id-7000610218.firebaseio.com',
    storageBucket: 'admob-app-id-7000610218.appspot.com',
    androidClientId: '1080350293673-02286ielujcje7ght01pd0ejnmoqufnl.apps.googleusercontent.com',
    iosClientId: '1080350293673-1cd0u1h7971hlcp5t6k3h0blr78ppdrb.apps.googleusercontent.com',
    iosBundleId: 'com.tuhin.cashMemoCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRWuPPpIK_NgQXKSKG8GsLaw9E_OF-bE',
    appId: '1:1080350293673:ios:adb33e8bd5a294c0ed33b8',
    messagingSenderId: '1080350293673',
    projectId: 'admob-app-id-7000610218',
    databaseURL: 'https://admob-app-id-7000610218.firebaseio.com',
    storageBucket: 'admob-app-id-7000610218.appspot.com',
    androidClientId: '1080350293673-02286ielujcje7ght01pd0ejnmoqufnl.apps.googleusercontent.com',
    iosClientId: '1080350293673-1cd0u1h7971hlcp5t6k3h0blr78ppdrb.apps.googleusercontent.com',
    iosBundleId: 'com.tuhin.cashMemoCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYLSevZcpfGMFNEIn-FDfGpONa8FZL0Ac',
    appId: '1:1080350293673:web:b61b1e8ecc9a2868ed33b8',
    messagingSenderId: '1080350293673',
    projectId: 'admob-app-id-7000610218',
    authDomain: 'admob-app-id-7000610218.firebaseapp.com',
    databaseURL: 'https://admob-app-id-7000610218.firebaseio.com',
    storageBucket: 'admob-app-id-7000610218.appspot.com',
    measurementId: 'G-JC924E8WK6',
  );

}